import Head from "next/head";
import type { NextPage } from "next";
import { ImageItem } from "src/components/Common/ImageItem";
import { TextItem } from "src/components/Common/TextItem";
import { MainLayout } from "src/components/Layout/MainLayout";

const About: NextPage = () => {
  return (
    <>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout>
        <h1 className="text-6xl font-bold">About</h1>
        <section className="mb-40 flex flex-col space-y-12">
          <ImageItem />
          <TextItem text="すべて人は、人種、皮膚の色、性、言語、宗教、" />
          <TextItem text="政治上その他の意見、国民的もしくは" />
          <TextItem text="社会的出身、財産、門地その他の地位又は" />
          <TextItem text="これに類するいかなる" />
          <TextItem text="自由による差別をも受けることなく、" />
        </section>
      </MainLayout>
    </>
  );
};

export default About;
