import Head from "next/head";
import { TextItem } from "../components/TextItem";
import type { NextPage } from "next";
import { ImageItem } from "src/components/ImageItem";
import { Layout } from "src/components/Layout";

const About: NextPage = () => {
  return (
    <>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <h1 className="text-6xl font-bold">About</h1>
        <section className="mb-40 flex flex-col space-y-12">
          <ImageItem />
          <TextItem text="ようこそ、ここからの世界へ。" />
          <TextItem text="次の文字は" />
          <TextItem text="動き出し、早くなる。" />
          <TextItem text="ようこそ、ここからの世界へ。" />
          <TextItem text="次の文字は" />
        </section>
      </Layout>
    </>
  );
};

export default About;
