import Head from "next/head";
import type { NextPage } from "next";
import { ImageItem } from "src/components/Common/ImageItem";
import { TextItem } from "src/components/Common/TextItem";
import { MainLayout } from "src/components/Layout/MainLayout";

const About: NextPage = () => {
  return (
    <>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout>
        <h1 className="text-6xl font-bold">About</h1>
        <section className="mb-40 flex flex-col space-y-12">
          <ImageItem />
          <TextItem text="ようこそ、ここからの世界へ。" />
          <TextItem text="次の文字は" />
          <TextItem text="動き出し、早くなる。" />
          <TextItem text="ようこそ、ここからの世界へ。" />
          <TextItem text="次の文字は" />
        </section>
      </MainLayout>
    </>
  );
};

export default About;
