import Head from "next/head";
import React from "react";
import { TextItem } from "src/components/Common/TextItem";
import { MainLayout } from "src/components/Layout/MainLayout";
import { ContactForm } from "src/components/pages/contact/ContactForm";

const Contact = () => {
  return (
    <>
      <Head>
        <title>Contact Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout>
        <section className="mb-20 flex flex-col space-y-12 md:mb-40">
          <div className="h-24 md:h-60" />
          <TextItem text="CONTACT" />
          <ContactForm />
        </section>
      </MainLayout>
    </>
  );
};

export default Contact;
