import Head from "next/head";
import React from "react";
import { ContactForm } from "@components/pages/form/ContactForm";
import { MainLayout } from "src/components/Layout/MainLayout";

const Contact = () => {
  return (
    <>
      <Head>
        <title>Contact Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout>
        <section className="mb-20 flex flex-col space-y-12 md:mb-40">
          <ContactForm formUID={process.env.NEXT_PUBLIC_CONTACT_FORM_UID} />
        </section>
      </MainLayout>
    </>
  );
};

export default Contact;
