import Head from "next/head";
import React from "react";
import { EventForm } from "@components/pages/form/EventForm";
import { MainLayout } from "src/components/Layout/MainLayout";

const Event = () => {
  return (
    <>
      <Head>
        <title>Contact Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout>
        <div className="mb-20 md:mb-40">
          <EventForm />
        </div>
      </MainLayout>
    </>
  );
};

export default Event;
