import Head from "next/head";
import type { NextPage } from "next";

const Home: NextPage = () => (
  <div>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>
      <h1 className="font-bold text-red-500">Welcome</h1>
    </main>
  </div>
);

export default Home;
