import { motion } from "framer-motion";
import Head from "next/head";
import Image from "next/image";
import { TextItem } from "../components/TextItem";
import type { NextPage } from "next";
import { Layout } from "src/components/Layout";
import { useRevealImage } from "src/hooks/useRevealImage";

const NewsImage = () => {
  const { ref, variants, control } = useRevealImage();
  return (
    <div className="mb-20">
      <motion.div
        ref={ref}
        initial="hidden"
        animate={control}
        variants={variants}
        className="mb-5"
      >
        <div className="relative h-[260px] w-[400px] overflow-hidden rounded-md">
          <Image
            src="/image-05.jpg"
            alt="image"
            layout="fill"
            objectFit="cover"
            className="transition duration-300 hover:scale-110"
          />
        </div>
      </motion.div>
      <div className="mb-4 flex items-center space-x-4 text-gray-400">
        <span className="rounded-full border-2 border-green-400 px-2 py-1 text-xs text-green-400">
          お知らせ
        </span>
        <span>Oct.27.2022</span>
      </div>
      <p className="w-[400px] text-xl">
        相模原線(小田急線)から弊社への乗り換えについてについて
      </p>
    </div>
  );
};

const News: NextPage = () => {
  return (
    <>
      <Head>
        <title>News Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <section className="mb-[140px] flex flex-col px-20">
          <div className="h-[320px]" />
          <TextItem text="NEWS" />
          <div className="grid grid-cols-4">
            <NewsImage />
            <NewsImage />
            <NewsImage />
            <NewsImage />
            <NewsImage />
            <NewsImage />
            <NewsImage />
            <NewsImage />
          </div>
        </section>
      </Layout>
    </>
  );
};

export default News;
