import { LightBulbIcon } from "@heroicons/react/24/solid";
import { MediaQuery, Tabs } from "@mantine/core";
import Head from "next/head";
import type { GetStaticProps, NextPage } from "next";
import { newtClient } from "@libs/newtClient";
import { CategoryType, QAType, SortedQAListType } from "@types";
import { MainLayout } from "src/components/Layout/MainLayout";
import { QuestionAccordion } from "src/components/pages/question/QuestionAccordion";

type Props = {
  sortedAllQandA: SortedQAListType[];
};

const Question: NextPage<Props> = ({ sortedAllQandA }) => {
  return (
    <>
      <Head>
        <title>Question Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout>
        <section className="mb-[140px] flex flex-col px-5 xl:px-20">
          <MediaQuery smallerThan="sm" styles={{ display: "none" }}>
            <Tabs defaultValue="1" variant="pills">
              <Tabs.List>
                {sortedAllQandA.map((questions) => (
                  <div key={questions.id}>
                    <Tabs.Tab
                      value={questions.id.toString()}
                      fz="lg"
                      fw="bold"
                      icon={<LightBulbIcon className="h-6 text-yellow-400" />}
                    >
                      {questions.title}
                    </Tabs.Tab>
                  </div>
                ))}
              </Tabs.List>
              {sortedAllQandA.map((questions) => (
                <Tabs.Panel
                  key={questions.id}
                  value={questions.id.toString()}
                  pt="xs"
                >
                  <QuestionAccordion contents={questions.contents} />
                </Tabs.Panel>
              ))}
            </Tabs>
          </MediaQuery>

          {sortedAllQandA.map((questions) => (
            <div key={questions.id} className="md:hidden">
              <div className="mb-3 flex items-center space-x-2">
                <LightBulbIcon className="h-6 text-yellow-400" />

                <p className="text-xl font-bold">{questions.title}</p>
              </div>
              <QuestionAccordion contents={questions.contents} />
            </div>
          ))}
        </section>
      </MainLayout>
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const { items: allQandA } = await newtClient.getContents<QAType>({
    appUid: process.env.NEWT_QA_APP_UID,
    modelUid: process.env.NEWT_QA_APP_Q_AND_A_UID,
    query: {
      order: ["-_sys.customOrder"],
    },
  });
  const { items: categories } = await newtClient.getContents<CategoryType>({
    appUid: process.env.NEWT_QA_APP_UID,
    modelUid: process.env.NEWT_CATEGORY_UID,
    query: {
      order: ["-_sys.customOrder"],
    },
  });

  const sortedAllQandA: SortedQAListType[] = categories.map(
    (category, index) => {
      const sortedItems = allQandA.filter(
        (qa) => qa.category._id === category._id
      );
      return {
        id: index + 1,
        title: category.category,
        contents: sortedItems,
      };
    }
  );

  return {
    props: {
      sortedAllQandA,
    },
  };
};

export default Question;
